[dependencies]
  cjbind = { path = "../cjbind" }

[package]
  cjc-version = "1.1.0"
  compile-option = "-Woff unused -V"
  description = "CLI for cjbind - C binding generator for Cangjie"
  link-option = "${LDFLAGS}"
  name = "cjbind_cli"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "0.2.10"

[profile.customized-option]
  cfg_opt = "-O2"
  cfg_verbose = "-V"

[target.x86_64-w64-mingw32.release]
  compile-option = "-O2"

[target.aarch64-apple-darwin.release]
  compile-option = "-O2"
  link-option = "-no_data_const"

[target.x86_64-unknown-linux-gnu.release]
  compile-option = "-O2"

[target.aarch64-unknown-linux-gnu.release]
  compile-option = "-O2"
