[dependencies]
  cjbind = { path = "../cjbind" }
  glob = { git = "https://github.com/Zxilly/glob-cj.git", tag = "v0.2.0" }

[package]
  cjc-version = "1.0.4"
  name = "cjbind_test"
  output-type = "executable"
  version = "0.2.9"
